CSS_DIR = 'CSS/GitHub'
CSS_PATH = []

WKH2P_PATH = ''

[WKH2P_OPTION]
margin-top = '0.75in'
margin-right = '0.75in'
margin-bottom = '0.75in'
margin-left = '0.75in'
encoding = 'UTF-8'
disable-smart-shrinking = ''
outline-depth = 10